[versions]
#project-name = "XiaomiHelper"
project-name = "RedMagicHelper"
android-compileSdk = "36"
android-minSdk = "34"
android-targetSdk = "36"
project-app-packageName = "dev.lackluster.redmagichelper"
project-app-versionName = "3.3.9"
project-app-versionCode = "260914"
capsule = "2.1.0"

androidGradlePlugin = "8.12.3"
kotlin = "2.2.20"


# Hook API
libxposed = "102.0.0"
libxposed-service = "101.0.0"
kavaref = "1.0.2"
kavaref-extension = "1.0.1"

dexkit = "2.0.7"
serialization-json = "1.9.0"
remoteCreationCore = "1.0.0-alpha03"

[libraries]
# Hook API
libxposed-api = { module = "io.github.libxposed:api", version.ref = "libxposed" }
libxposed-service = { module = "io.github.libxposed:service", version.ref = "libxposed-service" }
kavaref-extension = { module = "com.highcapable.kavaref:kavaref-extension", version.ref = "kavaref-extension" }
kavaref-core = { module = "com.highcapable.kavaref:kavaref-core", version.ref = "kavaref" }


androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version = "1.7.1" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version = "2.2.1" }
androidx-constraintlayout-compose = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version = "1.1.1" }
capsule = { module = "com.github.Kyant0:Capsule", version.ref = "capsule" }

dexkit = { module = "org.luckypray:dexkit", version.ref = "dexkit" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization-json" }

androidx-ui = { group = "androidx.compose.ui", name = "ui", version = "1.9.3" }

androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version = "1.17.0" }

androidx-test-junit = { group = "androidx.test.ext", name = "junit", version = "1.3.0" }
androidx-test-espresso = { group = "androidx.test.espresso", name = "espresso-core", version = "3.7.0" }
junit = { group = "junit", name = "junit", version = "4.13.2" }
androidx-remote-creation-core = { group = "androidx.compose.remote", name = "remote-creation-core", version.ref = "remoteCreationCore" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }

kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
